M48
; DRILL file {KiCad (6.0.4-0)} date Saturday, 06 August 2022 at 14:41:30
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-06T14:41:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.589Y-1.3421
X1.589Y-5.0429
X5.2898Y-1.3421
X5.2898Y-5.0429
T0
M30
